LP-2243 Write unit tests for fetch_course_structures philu_command
philanthropy-u/edx-platform pull request #1747
Opened 2020-09-01 11:17 UTC by muak50

### Description

[LP-2243](https://philanthropyu.atlassian.net/browse/LP-2243)

2020-09-01 11:22 UTC, philanthropyu commented
Your PR has finished running tests. The following contexts failed:
* jenkins/python

2020-09-01 16:40 UTC, ahmed-faraz46 commented
jenkins run all

2020-09-01 16:44 UTC, philanthropyu commented
Your PR has finished running tests. The following contexts failed:
* jenkins/python

2020-09-01 17:02 UTC, ahmed-faraz46 commented
jenkins run all

2020-09-01 17:14 UTC, philanthropyu commented
Your PR has finished running tests. The following contexts failed:
* jenkins/python

2020-09-03 11:04 UTC, ahmed-faraz46 approved these changes
LGTM 👍

2020-09-04 07:45 UTC, zahid-arbisoft requested changes

2020-09-04 07:45 UTC, zahid-arbisoft commented on common/djangoapps/philu_commands/management/commands/tests/test_fetch_course_structures.py
> +    @mock.patch('philu_commands.management.commands.fetch_course_structures.generate_course_structure')
Please add class doc string

2020-09-04 07:45 UTC, zahid-arbisoft commented on common/djangoapps/philu_commands/management/commands/tests/test_fetch_course_structures.py
> +class TestFetchCourseStructure(ModuleStoreTestCase):
Can we write one more test with invalid course id and assert that `generate_course_structure` is not called

`assert not generate_course_structure.called`

2020-09-07 21:30 UTC, philanthropyu commented
Your PR has finished running tests. The following contexts failed:
* jenkins/python

2020-09-08 06:50 UTC, zahid-arbisoft approved these changes

2020-09-08 08:10 UTC, merged