LP-2303 LP-2294 Unit test and linting for assessment and autoscore ORA command
philanthropy-u/edx-platform pull request #1754
Opened 2020-09-03 17:20 UTC by zahid-arbisoft

### Description

**[LP-2303](https://philanthropyu.atlassian.net/browse/LP-2303)** Autoscore ORA command (Unit test only)
**[LP-2294](https://philanthropyu.atlassian.net/browse/LP-2294)** Fix all linting errors for assessment

**Notes**

1. All unit test for autoscore ORA command and openedx assessment included
2. Linitng of autoscore ORA command and openedx assessment included
3. iSort ran on all files
4. Fixed following linting issue particular to LP-2294

```
************* Module edx-platform.openedx.features.assessment.tests.factories
openedx/features/assessment/tests/factories.py:17: [C1001(old-style-class), StudentItemFactory.Meta] Old-style class defined.
openedx/features/assessment/tests/factories.py:31: [C1001(old-style-class), SubmissionFactory.Meta] Old-style class defined.
************* Module edx-platform.openedx.features.assessment.tests.test_helpers
openedx/features/assessment/tests/test_helpers.py:136: [W0212(protected-access), AssessmentHelperModuleStoreTestCase.test_get_submissions_to_autoscore_by_enrollment_successfully] Access to a protected member _get_submissions_to_autoscore_by_enrollment of a client class
openedx/features/assessment/tests/test_helpers.py:154: [W0212(protected-access), AssessmentHelperModuleStoreTestCase.test_get_submissions_to_autoscore_by_enrollment_no_submissions] Access to a protected member _get_submissions_to_autoscore_by_enrollment of a client class
openedx/features/assessment/tests/test_helpers.py:174: [W0212(protected-access), AssessmentHelperModuleStoreTestCase.test_get_submissions_to_autoscore_by_enrollment_course_without_ora] Access to a protected member _get_submissions_to_autoscore_by_enrollment of a client class
openedx/features/assessment/tests/test_helpers.py:223: [W0212(protected-access), AssessmentHelperTestCases.test_log_multiple_submissions_info_with_multiple_submissions] Access to a protected member _log_multiple_submissions_info of a client class
openedx/features/assessment/tests/test_helpers.py:233: [W0212(protected-access), AssessmentHelperTestCases.test_log_multiple_submissions_info_with_no_submissions] Access to a protected member _log_multiple_submissions_info of a client class
openedx/features/assessment/tests/test_helpers.py:16: [W0611(unused-import), ] Unused AssessmentPart imported from openassessment.assessment.models
openedx/features/assessment/tests/test_helpers.py:21: [W0611(unused-import), ] Unused StudentItemFactory imported from openedx.features.assessment.tests.factories

-----------------------------------
Your code has been rated at 9.62/10
```

2020-09-04 07:15 UTC, philanthropyu commented
Your PR has finished running tests. The following contexts failed:
* jenkins/python

2020-09-04 07:46 UTC, philanthropyu commented
Your PR has finished running tests. The following contexts failed:
* jenkins/python

2020-09-04 09:38 UTC, philanthropyu commented
Your PR has finished running tests. The following contexts failed:
* jenkins/python

2020-09-04 09:43 UTC, philanthropyu commented
Your PR has finished running tests. The following contexts failed:
* jenkins/python

2020-09-08 13:49 UTC, harris-irfan requested changes

2020-09-08 13:49 UTC, harris-irfan commented on openedx/features/assessment/tests/test_helpers.py
> +        A helper function for tests, which create course enrollment, and perform submission for ORAs in course.
*creates
*performs

2020-09-08 13:49 UTC, harris-irfan commented on openedx/features/philu_utils/constants.py
> +    "vertical": "html",
single qoutes?

2020-09-08 13:51 UTC, harris-irfan commented
Aren't we supposed to either suppress the warnings in the pylint report, or solve them?

2020-09-09 08:55 UTC, zahid-arbisoft commented on common/djangoapps/philu_commands/management/commands/tests/test_autoscore_ondemand_course_ora.py
> +            expected_submission_uuids.insert(0, unicode(submission.uuid))
I have created a new test for testing these two states

2020-09-09 09:09 UTC, mabdullahz requested changes

2020-09-09 09:31 UTC, zahid-arbisoft commented on common/djangoapps/student/tests/factories.py
This is an already written code by us, I have just updated it, docstring is added for our own convenience, not for the sake of linting. Moving forward we can create factories in our code, but where will we keep factories?

2020-09-09 09:36 UTC, zahid-arbisoft commented on openedx/features/philu_utils/tests/mixins.py
> +    Base open assessment testcase class, with common methods to create courses dynamic, including ORA.
Updated to `to create course dynamically.`

2020-09-09 09:41 UTC, zahid-arbisoft commented on common/djangoapps/philu_commands/management/commands/tests/test_autoscore_ondemand_course_ora.py
> +from django.core.management import call_command
`iSort` wan ran on all files

2020-09-09 09:43 UTC, zahid-arbisoft commented on common/djangoapps/philu_commands/management/commands/tests/test_autoscore_ondemand_course_ora.py
> +# pylint: disable=redefined-outer-name
We cannot, this is how we use pytest fixture (another way is to use decorator) and it should be named exactly how it was defined.

2020-09-09 10:13 UTC, philanthropyu commented
Your PR has finished running tests. The following contexts failed:
* jenkins/python

2020-09-09 10:37 UTC, mabdullahz commented on common/djangoapps/student/tests/factories.py
Makes sense. I think we can look for a better place moving forward :)

2020-09-09 10:40 UTC, mabdullahz approved these changes

2020-09-09 10:42 UTC, harris-irfan approved these changes

2020-09-09 10:53 UTC, merged