LP-2303 Handling multiple objects returned by AnonymousUserId
philanthropy-u/edx-platform pull request #1760
Opened 2020-09-09 16:05 UTC by zahid-arbisoft

### Description

[LP-2303](https://philanthropyu.atlassian.net/browse/LP-2303) Auto score ORA command

### Notes

If `AnonymousUserId` model have more than one anonymous user ids against a combination of user and course then do not auto score, to avoid a crash.

2020-09-09 16:16 UTC, philanthropyu commented
Your PR has finished running tests. The following contexts failed:
* jenkins/python

2020-09-10 07:08 UTC, muak50 approved these changes
LGTM 👍

2020-09-10 07:13 UTC, ahmed-faraz46 requested changes

2020-09-10 07:13 UTC, ahmed-faraz46 commented on openedx/features/assessment/helpers.py
> +        # If AnonymousUserId model have more than one anonymous user ids against a combination of user and course then
Let's please make it a `TODO` comment.

2020-09-10 07:33 UTC, ahmed-faraz46 approved these changes
LGTM 👍

2020-09-10 07:34 UTC, merged

2020-09-10 07:35 UTC, philanthropyu commented
Your PR has finished running tests. The following contexts failed:
* jenkins/python