LP-2303 Fixing datetime inconsistency in delta and created at
philanthropy-u/edx-platform pull request #1764
Opened 2020-09-11 12:31 UTC by zahid-arbisoft

### Description

[LP-2303](https://philanthropyu.atlassian.net/browse/LP-2303) ORA auto score command

[philu-edx-theme PR](https://github.com/philanthropy-u/philu-edx-theme/pull/###)

The delta calculated from current DateTime and ORA number of day to wait was taken as date (instead of DateTime) and was compared to the date value of `created_at`. It was working fine on local but was not working on the dev server.

Now all dates `delta` and `crrated_at` are compared as UTC DateTime. This works on both servers, local and dev.

### Notes

- Unit test updated
- All unit test are passing

2020-09-11 12:50 UTC, philanthropyu commented
Your PR has finished running tests. The following contexts failed:
* jenkins/python

2020-09-11 13:48 UTC, mabdullahz approved these changes
LGTM :+1:

2020-09-11 14:50 UTC, emraan004 requested changes

2020-09-11 14:50 UTC, emraan004 commented on openedx/features/assessment/helpers.py
> +    delta_date = datetime.now(utc) - timedelta(days=days_to_wait)
now this variable `delta_date ` contains datetime instead of date, right? can we rename it so that it gives proper info?

2020-09-11 15:20 UTC, philanthropyu commented
Your PR has finished running tests. The following contexts failed:
* jenkins/python

2020-09-11 15:32 UTC, emraan004 approved these changes
LGTM 👍

2020-09-11 16:44 UTC, merged

2020-09-14 17:42 UTC, philanthropyu commented
Your PR has finished running tests. The following contexts failed:
* jenkins/python