LP-2433 Integrate msp_dashboard with edx-platform.
philanthropy-u/edx-platform pull request #1829
Opened 2020-11-04 15:04 UTC by qasimgulzar

### Description
[LP-2433](https://philanthropyu.atlassian.net/browse/LP-2433)

2020-11-04 15:09 UTC, philanthropyu commented
Your PR has finished running tests. The following contexts failed:
* jenkins/python

2020-11-04 15:09 UTC, philanthropyu commented
Your PR has finished running tests. The following contexts failed:
* jenkins/python

2020-11-04 15:15 UTC, ahmed-faraz46 requested changes

2020-11-04 15:15 UTC, ahmed-faraz46 commented on lms/envs/common.py
> +    'msp_assessment.msp_dashboard',
It looks like under the heading of `# Third party action planner xblock goals tracking application`. How about adding a separate heading for it or just adding separator.

2020-11-04 15:17 UTC, saad-waqar approved these changes

2020-11-04 16:03 UTC, philanthropyu commented
Your PR has finished running tests. The following contexts failed:
* jenkins/python

2020-11-05 07:22 UTC, ahmed-faraz46 approved these changes
LGTM 👍

2020-11-05 11:05 UTC, merged