Munam/lp 2291
philanthropy-u/edx-platform pull request #1864
Opened 2021-02-10 15:30 UTC by MunamMubashir-arbisoft

[LP-2291](https://philanthropyu.atlassian.net/browse/LP-2291)

- Fix pylint issues for the _student_certificates_ application
- Run isort for all the files

6 out 15 tests were failing even prior to the linting changes, kindly ignore those.

2021-02-10 16:02 UTC, emraan004 approved these changes
Looks good 👍 
There are some code changes/refactoring, please communicate with QA team to test those part in particular.

2021-02-11 05:35 UTC, harris-irfan requested changes
Please have a look at the failing isort check.

2021-02-11 05:35 UTC, harris-irfan commented on openedx/features/student_certificates/__init__.py
> +init file for student_certificates ap
app

2021-02-11 05:35 UTC, harris-irfan commented on openedx/features/student_certificates/handlers.py
> +                                             *_args, **_kwargs):  # pylint: disable=unused-argument
Let's please follow the edx [recommendations](https://edx.readthedocs.io/projects/edx-developer-guide/en/latest/style_guides/python-guidelines.html#breaking-long-lines) regarding breaking long lines.

2021-02-11 05:35 UTC, harris-irfan commented on openedx/features/student_certificates/tests/test_views.py
> +                                             course_open_date=get_current_utc_date())
Let's please follow the edx [recommendations](https://edx.readthedocs.io/projects/edx-developer-guide/en/latest/style_guides/python-guidelines.html#breaking-long-lines) regarding breaking long lines.

2021-02-11 08:59 UTC, annas-usman requested changes

2021-02-11 08:59 UTC, annas-usman commented on openedx/features/student_certificates/handlers.py
> +
Lets remove this extra line

2021-02-11 08:59 UTC, annas-usman commented on openedx/features/student_certificates/helpers.py
> +
Lets remove this extra line as well

2021-02-11 08:59 UTC, annas-usman commented on openedx/features/student_certificates/models.py
> +
Lets remove this extra line as well

2021-02-11 09:51 UTC, annas-usman approved these changes
LGTM

2021-02-11 09:54 UTC, MunamMubashir-arbisoft commented
The failing isort command is due to skipping one file for some unknown reason.
However, isort has been run of all the files locally and no error is being reported over there.
@harris-irfan

2021-02-11 11:07 UTC, harris-irfan approved these changes

2021-02-11 13:30 UTC, merged